spring:
  data:
    mongodb:
      uri: mongodb://spring-library:spring-library@cluster0-shard-00-00-saocz.mongodb.net:27017,cluster0-shard-00-01-saocz.mongodb.net:27017,cluster0-shard-00-02-saocz.mongodb.net:27017/test?ssl=true&replicaSet=Cluster0-shard-0&authSource=admin&retryWrites=true&w=majority
      database: spring-library
logging:
  level:
    org:
      springframework:
        security: trace
ru:
  otus:
    springlibrary:
      configuration:
        # checkTokenEndpointURL: https://spring-library-auth.herokuapp.com/oauth/check_token
        checkTokenEndpointURL: http://localhost:8081/oauth/check_token
        resourceId: spring-library-oauth2-server
        clientId: spring-library-jwt-client
        clientSecret: admin1234